import PageLayout from './PageLayout'

const heritageImages={
  about:[
    {src:'https://commons.wikimedia.org/wiki/Special:FilePath/MAHATMA_fule_vada_(22).JPG?width=1200',alt:'Mahatma Phule Wada in Pune',credit:'Mahatma Phule Wada, Wikimedia Commons',source:'https://commons.wikimedia.org/wiki/File:MAHATMA_fule_vada_(22).JPG'},
    {src:'https://commons.wikimedia.org/wiki/Special:FilePath/Savitribai_Phule_with_Fatima_Sheikh.jpg?width=700',alt:'Savitribai Phule with Fatima Sheikh and students',credit:'Savitribai Phule with Fatima Sheikh, Wikimedia Commons',source:'https://commons.wikimedia.org/wiki/File:Savitribai_Phule_with_Fatima_Sheikh.jpg'}
  ],
  committee:[
    {src:'https://commons.wikimedia.org/wiki/Special:FilePath/Mahatma_Jyotiba_Phule.jpg?width=700',alt:'Portrait of Mahatma Jyotiba Phule',credit:'Mahatma Jyotiba Phule, Wikimedia Commons',source:'https://commons.wikimedia.org/wiki/File:Mahatma_Jyotiba_Phule.jpg'},
    {src:'https://commons.wikimedia.org/wiki/Special:FilePath/Savitribai_Phule_1998_stamp_of_India.jpg?width=700',alt:'Savitribai Phule commemorative stamp',credit:'Savitribai Phule stamp, Wikimedia Commons',source:'https://commons.wikimedia.org/wiki/File:Savitribai_Phule_1998_stamp_of_India.jpg'}
  ]
}

const common={
  en:{
    gallery:'Gallery',galleryIntro:'A growing collection of approved photographs of Bhide Wada and community activities.',photos:['Bhide Wada','Rehabilitation','Community','Events'],coming:'Photo coming soon',contact:'Contact Us',contactIntro:'Send an enquiry and a committee representative will respond when official details are available.',name:'Full name *',phone:'Mobile number *',email:'Email (optional)',message:'Your message',send:'Send enquiry →'
  },
  mr:{
    gallery:'गॅलरी',galleryIntro:'भिडे वाडा आणि समुदाय उपक्रमांची मंजूर छायाचित्रे येथे जोडली जातील.',photos:['भिडे वाडा','पुनर्वसन','समुदाय','कार्यक्रम'],coming:'छायाचित्र लवकरच उपलब्ध होईल',contact:'संपर्क',contactIntro:'आपली चौकशी पाठवा. अधिकृत तपशील उपलब्ध झाल्यावर समितीचा प्रतिनिधी प्रतिसाद देईल.',name:'पूर्ण नाव *',phone:'मोबाईल क्रमांक *',email:'ईमेल (ऐच्छिक)',message:'आपला संदेश',send:'चौकशी पाठवा →'
  }
}

const pages={
  en:{
    about:{title:'About Bhide Wada',intro:'Bhide Wada is a landmark of women’s public education and social reform in India.',sections:[
      ['Historical background',['Located at 257, Budhwar Peth, Bhide Wada holds a permanent place in modern Indian history. On 1 January 1848, Savitribai Phule and Jyotirao Phule defied harsh social norms to open India’s first indigenous school for girls here. The building was offered for this work by their progressive associate, Tatyasaheb Bhide.','After a long legal process involving commercial tenancy rights, the site was cleared for redevelopment as a national memorial.']],
      ['Historical highlights',['The Historic Well — In 1868, Mahatma Phule opened his private courtyard well to the public. This courageous act gave Dalit and formerly untouchable communities access to clean water, directly challenging caste discrimination.','The Living Museum — Visitors can explore preserved rooms and galleries with vintage photographs, handwritten scripts, and timelines tracing the rise of the Satyashodhak Samaj (Society of Truth Seekers).','The Central Court — The central courtyard honours Jyotirao and Savitribai Phule through bronze busts beneath the historic tree canopy.']],
      ['Bhide Wada National Memorial Site',['Location: 257, Budhwar Peth, Tulshibaug, Pune, Maharashtra 411002.','Significance: Birthplace of women’s public education in India.']]
    ]},
    projects:{title:'National Memorial: Planned Features',intro:'The proposed memorial combines modern public amenities with respect for nineteenth-century history.',sections:[
      ['Latest project update',['Pune Municipal Corporation (PMC) approved funding of approximately ₹7.19 crore in August 2024 for the Bhide Wada memorial. A PMC tender issued in June 2024 described a basement-plus-ground-plus-three-floor building, with an estimated construction area of about 1,289.58 square metres and an expected nine-month construction period.']],
      ['Exhibitions',['Audio-video presentations, holographic installations, and interactive galleries will present the lives and work of Savitribai and Jyotirao Phule.']],
      ['Skill development',['A dedicated computer training and skill-guidance centre is planned for girls and women.']],
      ['Public infrastructure',['The memorial plan includes a spacious public amphitheatre and custom-crafted busts of the social reformers.']]
    ]},
    committee:{title:'Leadership Profile: Nilesh Girme',intro:'President, Mahatma Phule Wada & Bhide Wada National Memorial Committee.',sections:[
      ['Profile',['Nilesh Girme is a Pune-based social leader and public figure working on cultural preservation, urban community representation, and youth empowerment. He serves as a stakeholder connecting community interests with local government bodies, including the Pune Municipal Corporation (PMC).']],
      ['Key roles and responsibilities',['President, Mahatma Phule Wada & Bhide Wada National Memorial Committee — He heads the action committee for the memorial’s structural transition and community coordination, working with state, urban-development, and municipal stakeholders.','City Chief (Shaharpramukh), Yuva Sena, Pune — a regional youth leadership role.','Public and civic representative — involved in local governance and civic representation in Ward No. 34-A under the Pune Municipal Corporation.']],
      ['Contributions to the memorial project',['Project coordination — supporting municipal efforts to advance construction and align project stakeholders.','Modern facilities — advocating for skill-development spaces, computer training for women, and historical digital galleries.','Stakeholder alignment — helping coordinate administrators and local residents during land acquisition and rehabilitation processes.']],
      ['Official social profiles',['Instagram: @nilesh_girme2222','Facebook: Nilesh Girme Official']]
    ]},
    news:{title:'News & Updates',intro:'Official notices, meeting outcomes, and project progress will be published here after committee approval.',sections:[]},events:{title:'Events',intro:'Find information about heritage walks, public discussions, resident meetings, and educational programmes.',sections:[]},membership:{title:'Membership / Participate',intro:'Contact the committee to help preserve Bhide Wada’s history, share information, or join its activities.',sections:[]},documents:{title:'Documents / Downloads',intro:'Official reports, notices, applications, circulars, and rehabilitation-related documents will be available here.',sections:[]}
  },
  mr:{
    about:{title:'भिडे वाड्याची ओळख',intro:'भिडे वाडा हा भारतातील स्त्रियांच्या सार्वजनिक शिक्षणाचा आणि सामाजिक सुधारणेचा महत्त्वाचा ऐतिहासिक वारसा आहे.',sections:[
      ['ऐतिहासिक पार्श्वभूमी',['२५७, बुधवार पेठ येथे असलेल्या भिडे वाड्याला आधुनिक भारतीय इतिहासात कायमचे स्थान आहे. १ जानेवारी १८४८ रोजी सावित्रीबाई आणि ज्योतिराव फुले यांनी कठोर सामाजिक रूढींना आव्हान देत येथे भारतातील मुलींसाठी पहिली स्वदेशी शाळा सुरू केली. ही जागा त्यांचे पुरोगामी सहकारी तात्यासाहेब भिडे यांनी उपलब्ध करून दिली होती.','व्यावसायिक भाडेहक्कांबाबतच्या दीर्घ कायदेशीर प्रक्रियेनंतर या ठिकाणाचा राष्ट्रीय स्मारक म्हणून पुनर्विकासाचा मार्ग मोकळा झाला.']],
      ['ऐतिहासिक वैशिष्ट्ये',['ऐतिहासिक विहीर — १८६८ मध्ये महात्मा फुले यांनी त्यांच्या खाजगी अंगणातील विहीर सर्वांसाठी खुली केली. या धाडसी निर्णयामुळे दलित आणि तत्कालीन अस्पृश्य समाजाला स्वच्छ पाण्याचा हक्क मिळाला आणि जातीय भेदभावाला थेट आव्हान दिले गेले.','जिवंत संग्रहालय — जतन केलेल्या खोल्या व दालनांमध्ये दुर्मीळ जुनी छायाचित्रे, हस्तलिखिते आणि सत्यशोधक समाजाच्या उदयाचा इतिहास सांगणारी कालरेषा पाहता येईल.','मध्यवर्ती अंगण — ऐतिहासिक वृक्षछायेतील मध्यवर्ती अंगणात ज्योतिराव आणि सावित्रीबाई फुले यांच्या कांस्य प्रतिमांना अभिवादन करता येईल.']],
      ['भिडे वाडा राष्ट्रीय स्मारक स्थळ',['पत्ता: २५७, बुधवार पेठ, तुळशीबाग, पुणे, महाराष्ट्र ४११००२.','महत्त्व: भारतातील स्त्रियांच्या सार्वजनिक शिक्षणाचे जन्मस्थान.']]
    ]},
    projects:{title:'राष्ट्रीय स्मारक: नियोजित सुविधा',intro:'प्रस्तावित स्मारकात एकोणिसाव्या शतकाच्या इतिहासाला आदर देत आधुनिक सार्वजनिक सुविधा समाविष्ट केल्या जातील.',sections:[['अद्ययावत प्रकल्प माहिती',['पुणे महानगरपालिकेने (पीएमसी) ऑगस्ट २०२४ मध्ये भिडे वाडा स्मारकासाठी अंदाजे ₹७.१९ कोटी निधी मंजूर केला. जून २०२४ मधील पीएमसी निविदेनुसार तळघर, तळमजला आणि तीन मजल्यांची इमारत प्रस्तावित आहे. बांधकाम क्षेत्र सुमारे १,२८९.५८ चौ.मी. असून कामाचा अपेक्षित कालावधी नऊ महिने सांगण्यात आला होता.']],['प्रदर्शने',['सावित्रीबाई आणि ज्योतिराव फुले यांचे जीवन व कार्य मांडणारी ध्वनी-दृश्य सादरीकरणे, होलोग्राफिक मांडणी आणि संवादात्मक दालने.']],['कौशल्य विकास',['मुली आणि महिलांसाठी स्वतंत्र संगणक प्रशिक्षण व कौशल्य मार्गदर्शन केंद्राची योजना आहे.']],['सार्वजनिक पायाभूत सुविधा',['प्रशस्त सार्वजनिक ॲम्फीथिएटर आणि समाजसुधारकांचे विशेष तयार केलेले पुतळे या आराखड्यात समाविष्ट आहेत.']]]},
    committee:{title:'नेतृत्व परिचय: निलेश गिर्मे',intro:'अध्यक्ष, महात्मा फुले वाडा आणि भिडे वाडा राष्ट्रीय स्मारक समिती.',sections:[['परिचय',['निलेश गिर्मे हे पुण्यातील सामाजिक नेते व सार्वजनिक व्यक्तिमत्त्व आहेत. सांस्कृतिक जतन, शहरी समुदाय प्रतिनिधित्व आणि युवा सक्षमीकरणासाठी ते कार्यरत आहेत. पुणे महानगरपालिका (पीएमसी) यांसारख्या स्थानिक संस्थांशी समुदायाच्या हितसंबंधांचा संवाद साधण्यात त्यांची भूमिका आहे.']],['प्रमुख भूमिका व जबाबदाऱ्या',['अध्यक्ष, महात्मा फुले वाडा आणि भिडे वाडा राष्ट्रीय स्मारक समिती — स्मारकाच्या संरचनात्मक बदल व समुदाय समन्वयासाठी ते कृती समितीचे नेतृत्व करतात.','शहरप्रमुख, युवा सेना, पुणे — प्रादेशिक युवा नेतृत्वाची भूमिका.','सार्वजनिक व नागरी प्रतिनिधी — पुणे महानगरपालिकेच्या प्रभाग क्रमांक ३४-अ मध्ये नागरी प्रतिनिधित्व व स्थानिक प्रशासनात सहभाग.']],['स्मारक प्रकल्पातील योगदान',['प्रकल्प समन्वय — बांधकाम पुढे नेण्यासाठी आणि विविध भागधारकांमध्ये समन्वय राखण्यासाठी पालिकेच्या प्रयत्नांना पाठिंबा.','आधुनिक सुविधा — कौशल्य विकास, महिलांसाठी संगणक प्रशिक्षण आणि डिजिटल ऐतिहासिक दालनांसाठी पाठपुरावा.','भागधारक समन्वय — भूसंपादन व पुनर्वसन प्रक्रियेत प्रकल्प प्रशासन आणि स्थानिक रहिवाशांमध्ये समन्वय.']],['अधिकृत सामाजिक प्रोफाइल',['इन्स्टाग्राम: @nilesh_girme2222','फेसबुक: Nilesh Girme Official']]]},
    news:{title:'बातम्या व अपडेट्स',intro:'समितीच्या मंजुरीनंतर अधिकृत सूचना, बैठकींचे निष्कर्ष आणि प्रकल्प प्रगती येथे प्रसिद्ध केली जाईल.',sections:[]},events:{title:'कार्यक्रम',intro:'वारसा फेऱ्या, जनसंवाद, रहिवासी बैठका आणि शैक्षणिक कार्यक्रमांची माहिती येथे मिळेल.',sections:[]},membership:{title:'सदस्यत्व / सहभागी व्हा',intro:'भिडे वाड्याचा इतिहास जपण्यासाठी, माहिती देण्यासाठी किंवा उपक्रमांत सहभागी होण्यासाठी समितीशी संपर्क साधा.',sections:[]},documents:{title:'दस्तऐवज / डाउनलोड्स',intro:'अधिकृत अहवाल, सूचना, अर्ज, परिपत्रके आणि पुनर्वसनाशी संबंधित कागदपत्रे येथे उपलब्ध केली जातील.',sections:[]}
  }
}

export function ContentPage({type,language='mr'}){const t=pages[language]||pages.mr;const page=t[type]||t.about;const images=heritageImages[type];const aboutProfile=type==='about';return <PageLayout title={page.title} intro={page.intro}>{images&&<div className="heritage-image-grid">{images.map(image=><figure className="heritage-image" key={image.src}><img src={image.src} alt={image.alt}/><figcaption><a href={image.source} target="_blank" rel="noreferrer">{image.credit}</a></figcaption></figure>)}</div>}{page.sections.length?page.sections.map(([heading,paragraphs])=><section className="content-detail" key={heading}><p className="eyebrow">{heading}</p>{paragraphs.map(text=><p className="lead-copy" key={text}>{text}</p>)}</section>):<p className="lead-copy">{page.intro}</p>}{aboutProfile&&<section className="leader-profile"><img src="/assets/images/nilesh.png" alt="Nilesh Girme"/><div><p className="eyebrow">{language==='en'?'Leadership profile':'नेतृत्व परिचय'}</p><h2>{language==='en'?'Shri. Nileshbhau Radhikatai Dashrath Girme':'श्री. निलेशभाऊ राधिकाताई दशरथ गिरे'}</h2><p>{language==='en'?'President: Phule Wada and Bhide Wada National Memorial Committee':'अध्यक्ष : फुले वाडा व भिडे वाडा राष्ट्रीय स्मारक समिती'}</p></div></section>}{type==='projects'&&<p className="source-note">{language==='en'?'Sources: Hindustan Times (3 July 2024) and The Indian Express (13 August 2024).':'स्रोत: हिंदुस्तान टाइम्स (३ जुलै २०२४) आणि इंडियन एक्सप्रेस (१३ ऑगस्ट २०२४).'} <a href="https://www.hindustantimes.com/cities/pune-news/pmc-floats-7-26-crore-tender-for-savitribai-phule-memorial-at-bhidewada-101719944468507-amp.html" target="_blank" rel="noreferrer">{language==='en'?'Read source':'स्रोत वाचा'}</a></p>}</PageLayout>}
export function GalleryPage({language='mr'}){const t=common[language]||common.mr;return <PageLayout title={t.gallery} intro={t.galleryIntro}><div className="gallery-grid">{t.photos.map(item=><article className="gallery-card" key={item}><div className="gallery-placeholder">{item}<br/>{t.coming}</div></article>)}</div></PageLayout>}
export function ContactPage({language='mr'}){const t=common[language]||common.mr;const isEnglish=language==='en';return <PageLayout title={t.contact} intro={t.contactIntro}><div className="contact-page-grid"><aside className="contact-location"><p className="eyebrow">{isEnglish?'Visit the memorial site':'स्मारक स्थळाला भेट द्या'}</p><h2>{isEnglish?'Bhide Wada National Memorial':'भिडे वाडा राष्ट्रीय स्मारक'}</h2><p>{isEnglish?'Located in the historic Budhwar Peth area of Pune.':'पुण्यातील ऐतिहासिक बुधवार पेठ परिसरात स्थित.'}</p><div className="location-address"><span>⌖</span><b>{isEnglish?'257, Budhwar Peth, Tulshibaug':'२५७, बुधवार पेठ, तुळशीबाग'}</b><small>{isEnglish?'Pune, Maharashtra 411002':'पुणे, महाराष्ट्र ४११००२'}</small></div><a className="map-link" href="https://www.google.com/maps/search/?api=1&query=Bhide+Wada+Budhwar+Peth+Pune" target="_blank" rel="noreferrer">{isEnglish?'Open in Google Maps →':'Google Maps वर उघडा →'}</a></aside><form className="contact-form"><input placeholder={t.name} required/><input placeholder={t.phone} required/><input type="email" placeholder={t.email}/><textarea placeholder={t.message} rows="5"/><button className="primary">{t.send}</button></form></div></PageLayout>}
